/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AppBookingsRouteImport } from './routes/_app.bookings'
import { Route as AppComplaintsRouteImport } from './routes/_app.complaints'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppFoodRouteImport } from './routes/_app.food'
import { Route as AppMatchingRouteImport } from './routes/_app.matching'
import { Route as AppMyAssistantRouteImport } from './routes/_app.my-assistant'
import { Route as AppMyComplaintsRouteImport } from './routes/_app.my-complaints'
import { Route as AppMyFoodRouteImport } from './routes/_app.my-food'
import { Route as AppMyRoomRouteImport } from './routes/_app.my-room'
import { Route as AppMyVisitorsRouteImport } from './routes/_app.my-visitors'
import { Route as AppNoticesRouteImport } from './routes/_app.notices'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppPayRentRouteImport } from './routes/_app.pay-rent'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPropertiesRouteImport } from './routes/_app.properties'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRoomsRouteImport } from './routes/_app.rooms'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppStaffRouteImport } from './routes/_app.staff'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppTenantsRouteImport } from './routes/_app.tenants'
import { Route as AppVisitorsRouteImport } from './routes/_app.visitors'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as PgIdRouteImport } from './routes/pg.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsRoute = AppComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppFoodRoute = AppFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchingRoute = AppMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAssistantRoute = AppMyAssistantRouteImport.update({
  id: '/my-assistant',
  path: '/my-assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppMyComplaintsRoute = AppMyComplaintsRouteImport.update({
  id: '/my-complaints',
  path: '/my-complaints',
  getParentRoute: () => AppRoute,
} as any)
const AppMyFoodRoute = AppMyFoodRouteImport.update({
  id: '/my-food',
  path: '/my-food',
  getParentRoute: () => AppRoute,
} as any)
const AppMyRoomRoute = AppMyRoomRouteImport.update({
  id: '/my-room',
  path: '/my-room',
  getParentRoute: () => AppRoute,
} as any)
const AppMyVisitorsRoute = AppMyVisitorsRouteImport.update({
  id: '/my-visitors',
  path: '/my-visitors',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticesRoute = AppNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPayRentRoute = AppPayRentRouteImport.update({
  id: '/pay-rent',
  path: '/pay-rent',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesRoute = AppPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitorsRoute = AppVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AppRoute,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PgIdRoute = PgIdRouteImport.update({
  id: '/pg/$id',
  path: '/pg/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/bookings': typeof AppBookingsRoute
  '/complaints': typeof AppComplaintsRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/food': typeof AppFoodRoute
  '/matching': typeof AppMatchingRoute
  '/my-assistant': typeof AppMyAssistantRoute
  '/my-complaints': typeof AppMyComplaintsRoute
  '/my-food': typeof AppMyFoodRoute
  '/my-room': typeof AppMyRoomRoute
  '/my-visitors': typeof AppMyVisitorsRoute
  '/notices': typeof AppNoticesRoute
  '/notifications': typeof AppNotificationsRoute
  '/pay-rent': typeof AppPayRentRoute
  '/payments': typeof AppPaymentsRoute
  '/profile': typeof AppProfileRoute
  '/properties': typeof AppPropertiesRoute
  '/reports': typeof AppReportsRoute
  '/rooms': typeof AppRoomsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/tasks': typeof AppTasksRoute
  '/tenants': typeof AppTenantsRoute
  '/visitors': typeof AppVisitorsRoute
  '/book/$id': typeof BookIdRoute
  '/pg/$id': typeof PgIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/bookings': typeof AppBookingsRoute
  '/complaints': typeof AppComplaintsRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/food': typeof AppFoodRoute
  '/matching': typeof AppMatchingRoute
  '/my-assistant': typeof AppMyAssistantRoute
  '/my-complaints': typeof AppMyComplaintsRoute
  '/my-food': typeof AppMyFoodRoute
  '/my-room': typeof AppMyRoomRoute
  '/my-visitors': typeof AppMyVisitorsRoute
  '/notices': typeof AppNoticesRoute
  '/notifications': typeof AppNotificationsRoute
  '/pay-rent': typeof AppPayRentRoute
  '/payments': typeof AppPaymentsRoute
  '/profile': typeof AppProfileRoute
  '/properties': typeof AppPropertiesRoute
  '/reports': typeof AppReportsRoute
  '/rooms': typeof AppRoomsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/tasks': typeof AppTasksRoute
  '/tenants': typeof AppTenantsRoute
  '/visitors': typeof AppVisitorsRoute
  '/book/$id': typeof BookIdRoute
  '/pg/$id': typeof PgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/_app/bookings': typeof AppBookingsRoute
  '/_app/complaints': typeof AppComplaintsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/food': typeof AppFoodRoute
  '/_app/matching': typeof AppMatchingRoute
  '/_app/my-assistant': typeof AppMyAssistantRoute
  '/_app/my-complaints': typeof AppMyComplaintsRoute
  '/_app/my-food': typeof AppMyFoodRoute
  '/_app/my-room': typeof AppMyRoomRoute
  '/_app/my-visitors': typeof AppMyVisitorsRoute
  '/_app/notices': typeof AppNoticesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/pay-rent': typeof AppPayRentRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/properties': typeof AppPropertiesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/rooms': typeof AppRoomsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/tenants': typeof AppTenantsRoute
  '/_app/visitors': typeof AppVisitorsRoute
  '/book/$id': typeof BookIdRoute
  '/pg/$id': typeof PgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/bookings'
    | '/complaints'
    | '/dashboard'
    | '/expenses'
    | '/food'
    | '/matching'
    | '/my-assistant'
    | '/my-complaints'
    | '/my-food'
    | '/my-room'
    | '/my-visitors'
    | '/notices'
    | '/notifications'
    | '/pay-rent'
    | '/payments'
    | '/profile'
    | '/properties'
    | '/reports'
    | '/rooms'
    | '/settings'
    | '/staff'
    | '/tasks'
    | '/tenants'
    | '/visitors'
    | '/book/$id'
    | '/pg/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/bookings'
    | '/complaints'
    | '/dashboard'
    | '/expenses'
    | '/food'
    | '/matching'
    | '/my-assistant'
    | '/my-complaints'
    | '/my-food'
    | '/my-room'
    | '/my-visitors'
    | '/notices'
    | '/notifications'
    | '/pay-rent'
    | '/payments'
    | '/profile'
    | '/properties'
    | '/reports'
    | '/rooms'
    | '/settings'
    | '/staff'
    | '/tasks'
    | '/tenants'
    | '/visitors'
    | '/book/$id'
    | '/pg/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/browse'
    | '/_app/bookings'
    | '/_app/complaints'
    | '/_app/dashboard'
    | '/_app/expenses'
    | '/_app/food'
    | '/_app/matching'
    | '/_app/my-assistant'
    | '/_app/my-complaints'
    | '/_app/my-food'
    | '/_app/my-room'
    | '/_app/my-visitors'
    | '/_app/notices'
    | '/_app/notifications'
    | '/_app/pay-rent'
    | '/_app/payments'
    | '/_app/profile'
    | '/_app/properties'
    | '/_app/reports'
    | '/_app/rooms'
    | '/_app/settings'
    | '/_app/staff'
    | '/_app/tasks'
    | '/_app/tenants'
    | '/_app/visitors'
    | '/book/$id'
    | '/pg/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  BookIdRoute: typeof BookIdRoute
  PgIdRoute: typeof PgIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/bookings': {
      id: '/_app/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints': {
      id: '/_app/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AppComplaintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/food': {
      id: '/_app/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof AppFoodRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matching': {
      id: '/_app/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof AppMatchingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-assistant': {
      id: '/_app/my-assistant'
      path: '/my-assistant'
      fullPath: '/my-assistant'
      preLoaderRoute: typeof AppMyAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-complaints': {
      id: '/_app/my-complaints'
      path: '/my-complaints'
      fullPath: '/my-complaints'
      preLoaderRoute: typeof AppMyComplaintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-food': {
      id: '/_app/my-food'
      path: '/my-food'
      fullPath: '/my-food'
      preLoaderRoute: typeof AppMyFoodRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-room': {
      id: '/_app/my-room'
      path: '/my-room'
      fullPath: '/my-room'
      preLoaderRoute: typeof AppMyRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-visitors': {
      id: '/_app/my-visitors'
      path: '/my-visitors'
      fullPath: '/my-visitors'
      preLoaderRoute: typeof AppMyVisitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notices': {
      id: '/_app/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AppNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pay-rent': {
      id: '/_app/pay-rent'
      path: '/pay-rent'
      fullPath: '/pay-rent'
      preLoaderRoute: typeof AppPayRentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/properties': {
      id: '/_app/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AppPropertiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants': {
      id: '/_app/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visitors': {
      id: '/_app/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof AppVisitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pg/$id': {
      id: '/pg/$id'
      path: '/pg/$id'
      fullPath: '/pg/$id'
      preLoaderRoute: typeof PgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBookingsRoute: typeof AppBookingsRoute
  AppComplaintsRoute: typeof AppComplaintsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppFoodRoute: typeof AppFoodRoute
  AppMatchingRoute: typeof AppMatchingRoute
  AppMyAssistantRoute: typeof AppMyAssistantRoute
  AppMyComplaintsRoute: typeof AppMyComplaintsRoute
  AppMyFoodRoute: typeof AppMyFoodRoute
  AppMyRoomRoute: typeof AppMyRoomRoute
  AppMyVisitorsRoute: typeof AppMyVisitorsRoute
  AppNoticesRoute: typeof AppNoticesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPayRentRoute: typeof AppPayRentRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppPropertiesRoute: typeof AppPropertiesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRoomsRoute: typeof AppRoomsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTenantsRoute: typeof AppTenantsRoute
  AppVisitorsRoute: typeof AppVisitorsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookingsRoute: AppBookingsRoute,
  AppComplaintsRoute: AppComplaintsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppFoodRoute: AppFoodRoute,
  AppMatchingRoute: AppMatchingRoute,
  AppMyAssistantRoute: AppMyAssistantRoute,
  AppMyComplaintsRoute: AppMyComplaintsRoute,
  AppMyFoodRoute: AppMyFoodRoute,
  AppMyRoomRoute: AppMyRoomRoute,
  AppMyVisitorsRoute: AppMyVisitorsRoute,
  AppNoticesRoute: AppNoticesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPayRentRoute: AppPayRentRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProfileRoute: AppProfileRoute,
  AppPropertiesRoute: AppPropertiesRoute,
  AppReportsRoute: AppReportsRoute,
  AppRoomsRoute: AppRoomsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppTasksRoute: AppTasksRoute,
  AppTenantsRoute: AppTenantsRoute,
  AppVisitorsRoute: AppVisitorsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  BookIdRoute: BookIdRoute,
  PgIdRoute: PgIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
